[program:unit]
# Commant to start
command=/usr/sbin/unitd --no-daemon --statedir "/etc/unit" --log "/dev/stdout" --pid "/var/run/unit/unit.pid" --control "unix:/var/run/unit/control.sock"
# Process name
process_name=%(program_name)s_%(process_num)02d
# Workers count
numprocs=1
# Start config
autostart=true
# Restart config
autorestart=true
startretries=999999999999
# Redirect stdout to docker logs
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
# Redirect stdout to docker logs
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0