[program:background]
# Commant to start
command=/bin/sh -c "while (true); do /usr/bin/php -f /home/app/cron.php; sleep 5m; done"
# Process name
process_name=%(program_name)s_%(process_num)02d
# Workers count
numprocs=1
# Start config
autostart=true
# Restart config
autorestart=true
startretries=999999999999
# Redirect stdout to docker logs
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
# Redirect stdout to docker logs
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
