[unix_http_server]
# Control socket
file=/var/lib/supervisord/supervisor.sock

[supervisord]
# Nodaemonize
nodaemon=true
# Process file
pidfile=/run/supervisord/supervisord.pid
# Global logs
logfile=/dev/null
logfile_maxbytes=0

[supervisorctl]
serverurl=unix:///var/lib/supervisord/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[include]
files = /etc/supervisor/conf.d/*.conf
