name: "nextcloud"

services:
  app:
    image: tuzelko/nextcloud:latest
    environment:
      # Main configuration
      NEXTCLOUD_SCHEME: "https"
      NEXTCLOUD_DOMAINS: "localhost,cloud.example.com"
      NEXTCLOUD_MAIN_DOMAIN: "cloud.example.com"
      NEXTCLOUD_PHONE_REGION: "us"
      # DB configuration
      NEXTCLOUD_DB_TYPE: "mysql"
      NEXTCLOUD_DB_HOST: "database"
      NEXTCLOUD_DB_NAME: "nextcloud"
      NEXTCLOUD_DB_USER: "nextcloud"
      NEXTCLOUD_DB_PASSWORD: "CHANGE_ME"
      # Cache configuration
      NEXTCLOUD_CACHE_MODE: "redis"
      NEXTCLOUD_CACHE_REDIS_HOST: "cache"
      NEXTCLOUD_CACHE_REDIS_PORT: "6379"
      # Mail configuration
      NEXTCLOUD_SMTP_MODE: "smtp"
      NEXTCLOUD_SMTP_HOST: "smtp.example.com"
      NEXTCLOUD_SMTP_PORT: "465"
      NEXTCLOUD_SMTP_SECURE: "SSL"
      NEXTCLOUD_SMTP_AUTH: "true"
      NEXTCLOUD_SMTP_AUTH_TYPE: "LOGIN"
      NEXTCLOUD_SMTP_USER: "user@example.com"
      NEXTCLOUD_SMTP_PASSWORD: "CHANGE_ME"
      NEXTCLOUD_SMTP_DOMAIN: "example.com"
      NEXTCLOUD_SMTP_FROM: "cloud"
    labels:
      traefik.enable: true
      traefik.http.services.nextcloud-app-service.loadbalancer.server.port: 80
      traefik.http.routers.nextcloud-app-router.service: nextcloud-app-service
      traefik.http.routers.nextcloud-app-router.rule: "Host(`cloud.example.com`)"
      traefik.http.routers.nextcloud-app-router.entrypoints: "websecure"
      traefik.http.routers.nextcloud-app-router.tls: true
      traefik.http.routers.nextcloud-app-router.middlewares: "nextcloud-hsts"
      traefik.http.middlewares.nextcloud-hsts.headers.stsSeconds: 31536000
      traefik.docker.network: "ingress_global_network"
    networks:
      - global-network
      - database-network
      - cache-network
      - onlyoffice-network
    volumes:
      - app-scripts:/home/app
      - app-storage:/home/files
    healthcheck:
      test: [ "CMD", "/bin/healthcheck.sh" ]
      start_period: 30s
      start_interval: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      database:
        condition: service_healthy
      cache:
        condition: service_healthy
    restart: always

  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: "CHANGE_ME"
      MARIADB_USER: "nextcloud"
      MARIADB_PASSWORD: "CHANGE_ME"
      MARIADB_DATABASE: "nextcloud"
      MARIADB_AUTO_UPGRADE: "yes"
    networks:
      - database-network
    volumes:
      - database-storage:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 10s
      start_interval: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  cache:
    image: valkey/valkey:9-alpine
    networks:
      - cache-network
    healthcheck:
      test: [ "CMD", "valkey-cli", "-p", "6379", "ping" ]
      start_period: 10s
      start_interval: 5s
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - valkey-server
      - --port 6379
    restart: always

  onlyoffice:
    image: onlyoffice/documentserver:latest
    environment:
      JWT_SECRET: "CHANGE_ME" # Use: openssl rand -hex 64
    labels:
      traefik.enable: true
      traefik.http.services.nextcloud-onlyoffice-service.loadbalancer.server.port: 80
      traefik.http.routers.nextcloud-onlyoffice-router.service: nextcloud-onlyoffice-service
      traefik.http.routers.nextcloud-onlyoffice-router.rule: "Host(`cloud.example.com`) && PathPrefix(`/services/onlyoffice/`)"
      traefik.http.routers.nextcloud-onlyoffice-router.entrypoints: "websecure"
      traefik.http.routers.nextcloud-onlyoffice-router.tls: true
      traefik.http.routers.nextcloud-onlyoffice-router.middlewares: "nextcloud-onlyoffice-strip,nextcloud-onlyoffice-proto"
      traefik.http.middlewares.nextcloud-onlyoffice-strip.stripprefix.prefixes: "/services/onlyoffice"
      traefik.http.middlewares.nextcloud-onlyoffice-proto.headers.customrequestheaders.X-Forwarded-Proto: "https"
      traefik.docker.network: "ingress_global_network"
    networks:
      - global-network
      - onlyoffice-network
    restart: always

  talk:
    image: ghcr.io/nextcloud-releases/aio-talk:latest
    environment:
      NC_DOMAIN: "cloud.example.com"
      TALK_HOST: "talk.example.com"
      TALK_PORT: 3478
      TURN_SECRET: "CHANGE_ME" # Use: openssl rand -hex 64
      SIGNALING_SECRET: "CHANGE_ME" # Use: openssl rand -hex 64
      INTERNAL_SECRET: "CHANGE_ME" # Use: openssl rand -hex 64
    labels:
      traefik.enable: true
      traefik.http.services.nextcloud-talk-service.loadbalancer.server.port: 8081
      traefik.http.routers.nextcloud-talk-router.service: nextcloud-talk-service
      traefik.http.routers.nextcloud-talk-router.rule: "Host(`cloud.example.com`) && PathPrefix(`/services/talk/`)"
      traefik.http.routers.nextcloud-talk-router.entrypoints: "websecure"
      traefik.http.routers.nextcloud-talk-router.tls: true
      traefik.http.routers.nextcloud-talk-router.middlewares: "nextcloud-talk-strip"
      traefik.http.middlewares.nextcloud-talk-strip.stripprefix.prefixes: "/services/talk"
      traefik.docker.network: "ingress_global_network"
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
    networks:
      - global-network
    restart: always


volumes:
  app-scripts:
    driver: local
  app-storage:
    driver: local
  database-storage:
    driver: local


networks:
  global-network:
    external: true
    name: ingress_global_network
  database-network:
    driver: bridge
  cache-network:
    driver: bridge
  onlyoffice-network:
    driver: bridge
  talk-network:
    driver: bridge